name: Build River3 

on:
  push:
    branches: ["master", "dockerfile-improvements"]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./River3/Dockerfile
          context: ./River3
          push: true
          tags: cconache/river3:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
