name: test-river

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: 'recursive'
            - name: Check docker
              run: docker --version
            - name: Use docker to build test image
              run: make -C ./docker build
            - name: Use docker to run tests
              run: make -C ./docker test


